export const PLATFORM_EVENT_OPTIONS = {
    kirvano: [
        { value: 'SALE_APPROVED', label: 'Compra Aprovada' },
        { value: 'SALE_APPROVED_OB', label: 'Compra Aprovada + Order Bump' },
        { value: 'SALE_REFUSED', label: 'Compra Recusada' },
        { value: 'SALE_CANCELED', label: 'Compra Cancelada' },
        { value: 'SALE_REFUNDED', label: 'Reembolso' },
        { value: 'SALE_CHARGEBACK', label: 'Chargeback' },
        { value: 'BANK_SLIP_GENERATED', label: 'Boleto Gerado' },
        { value: 'BANK_SLIP_EXPIRED', label: 'Boleto Expirado' },
        { value: 'PIX_GENERATED', label: 'PIX Gerado' },
        { value: 'PIX_EXPIRED', label: 'PIX Expirado' },
        { value: 'ABANDONED_CART', label: 'Carrinho Abandonado' },
        { value: 'SUBSCRIPTION_CANCELED', label: 'Assinatura Cancelada' },
        { value: 'SUBSCRIPTION_EXPIRED', label: 'Assinatura Atrasada' },
        { value: 'SUBSCRIPTION_RENEWED', label: 'Assinatura Renovada' },
    ],
    hotmart: [
        { value: 'PURCHASE_APPROVED', label: 'Compra Aprovada' },
        { value: 'PURCHASE_APPROVED_OB', label: 'Compra Aprovada (Order Bump)' },
        { value: 'PURCHASE_CANCELED', label: 'Compra Cancelada' },
        { value: 'PURCHASE_REFUNDED', label: 'Reembolso' },
        { value: 'PURCHASE_CHARGEBACK', label: 'Chargeback' },
        { value: 'PURCHASE_PROTEST', label: 'Contestação / Disputa' },
        { value: 'PURCHASE_BILLET_PRINTED', label: 'Boleto Impresso' },
        { value: 'PURCHASE_COMPLETE', label: 'Compra Concluída' },
        { value: 'PURCHASE_DELAYED', label: 'Pagamento Atrasado' },
        { value: 'PURCHASE_EXPIRED', label: 'Compra Expirada' },
        { value: 'PURCHASE_OUT_OF_SHOPPING_CART', label: 'Checkout Pré-populado' },
        { value: 'ABANDONED_CART', label: 'Carrinho Abandonado' },
        { value: 'SUBSCRIPTION_CANCELLATION', label: 'Assinatura Cancelada' },
        { value: 'SWITCH_PLAN', label: 'Troca de Plano' },
        { value: 'UPDATE_SUBSCRIPTION_CHARGE_DATE', label: 'Data de Cobrança Alterada' },
        { value: 'CLUB_FIRST_ACCESS', label: 'Acesso ao Clube (1º acesso)' },
        { value: 'CLUB_MODULE_COMPLETED', label: 'Módulo do Clube Concluído' },
    ],
    kiwify: [
        { value: 'paid', label: 'Compra Aprovada' },
        { value: 'paid_ob', label: 'Compra Aprovada + Order Bump' },
        { value: 'refused', label: 'Cartão Recusado' },
        { value: 'refunded', label: 'Reembolso' },
        { value: 'chargeback', label: 'Chargeback' },
        { value: 'waiting_payment_boleto', label: 'Boleto Gerado' },
        { value: 'waiting_payment_pix', label: 'PIX Gerado' },
        { value: 'abandoned', label: 'Carrinho Abandonado' },
        { value: 'subscription_canceled', label: 'Assinatura Cancelada' },
        { value: 'subscription_late', label: 'Assinatura Atrasada' },
        { value: 'subscription_renewed', label: 'Assinatura Renovada' },
    ],
    eduzz: [
        { value: 'paid', label: 'Compra Aprovada' },
        { value: 'paid_with_bump', label: 'Compra Aprovada + Order Bump' },
        { value: 'canceled', label: 'Cancelado / Recusado' },
        { value: 'refunded', label: 'Reembolso' },
        { value: 'waiting_payment_boleto', label: 'Boleto Gerado' },
        { value: 'waiting_payment_pix', label: 'PIX Gerado' },
        { value: 'abandoned_cart', label: 'Carrinho Abandonado' },
        { value: 'nutror_aluno', label: 'Evento de Aluno (Nutror)' },
    ],
    ticto: [
        { value: 'purchase.approved', label: 'Compra Aprovada' },
        { value: 'purchase.approved_ob', label: 'Compra Aprovada + Order Bump' },
        { value: 'purchase.refused', label: 'Cartão Recusado' },
        { value: 'purchase.canceled', label: 'Compra Cancelada' },
        { value: 'purchase.refunded', label: 'Reembolso' },
        { value: 'purchase.chargeback', label: 'Chargeback' },
        { value: 'purchase.waiting_boleto', label: 'Boleto Gerado' },
        { value: 'purchase.waiting_pix', label: 'PIX Gerado' },
        { value: 'purchase.abandoned_cart', label: 'Carrinho Abandonado' },
        { value: 'subscription.canceled', label: 'Assinatura Cancelada' },
        { value: 'subscription.renewed', label: 'Assinatura Renovada' },
        { value: 'subscription.overdue', label: 'Assinatura Atrasada' },
        { value: 'subscription.late', label: 'Assinatura Atrasada (late)' },
    ],
    pepper: [
        { value: 'PURCHASE_APPROVED', label: 'Compra Aprovada' },
        { value: 'PURCHASE_APPROVED_OB', label: 'Compra Aprovada + Order Bump' },
        { value: 'PURCHASE_REFUSED', label: 'Cartão Recusado' },
        { value: 'PURCHASE_CANCELED', label: 'Compra Cancelada' },
        { value: 'PURCHASE_REFUNDED', label: 'Reembolso' },
        { value: 'PURCHASE_CHARGEBACK', label: 'Chargeback' },
        { value: 'BILLET_GENERATED', label: 'Boleto Gerado' },
        { value: 'PIX_GENERATED', label: 'PIX Gerado' },
        { value: 'ABANDONED_CART', label: 'Carrinho Abandonado' },
    ],
    braip: [
        { value: 'approved', label: 'Compra Aprovada' },
        { value: 'approved_ob', label: 'Compra Aprovada + Order Bump' },
        { value: 'refused', label: 'Cartão Recusado' },
        { value: 'canceled', label: 'Cancelada' },
        { value: 'refunded', label: 'Reembolso' },
        { value: 'chargeback', label: 'Chargeback' },
        { value: 'billet', label: 'Boleto Gerado' },
        { value: 'billet_pix', label: 'PIX Gerado' },
        { value: 'abandoned', label: 'Carrinho Abandonado' },
    ],
    monetizze: [
        { value: 'approved', label: 'Compra Aprovada' },
        { value: 'approved_ob', label: 'Compra Aprovada + Order Bump' },
        { value: 'canceled', label: 'Cartão Recusado / Cancelado' },
        { value: 'refunded', label: 'Reembolso / Estorno' },
        { value: 'chargeback', label: 'Chargeback' },
        { value: 'boleto', label: 'Boleto Gerado' },
        { value: 'pix', label: 'PIX Gerado' },
        { value: 'overdue', label: 'Assinatura Inadimplente' },
        { value: 'subscription_canceled', label: 'Assinatura Cancelada' },
        { value: 'subscription_renewed', label: 'Assinatura Renovada' },
        { value: 'abandoned', label: 'Carrinho Abandonado' },
    ],
    cakto: [
        { value: 'order.paid', label: 'Compra Aprovada' },
        { value: 'order.paid_ob', label: 'Compra Aprovada + Order Bump' },
        { value: 'order.refused', label: 'Cartão Recusado' },
        { value: 'order.canceled', label: 'Compra Cancelada' },
        { value: 'order.refunded', label: 'Reembolso' },
        { value: 'order.chargedback', label: 'Chargeback' },
        { value: 'order.billet_generated', label: 'Boleto Gerado' },
        { value: 'order.pix_generated', label: 'PIX Gerado' },
        { value: 'order.pix_expired', label: 'PIX Expirado' },
        { value: 'order.abandoned', label: 'Carrinho Abandonado' },
        { value: 'subscription.canceled', label: 'Assinatura Cancelada' },
        { value: 'subscription.renewed', label: 'Assinatura Renovada' },
        { value: 'subscription.overdue', label: 'Assinatura Atrasada' },
    ],
    lastlink: [
        { value: 'Purchase_Order_Confirmed', label: 'Compra Aprovada' },
        { value: 'Purchase_Order_Confirmed_Upsell', label: 'Compra Aprovada (Upsell)' },
        { value: 'Payment_Refund', label: 'Reembolso' },
        { value: 'Payment_Chargeback', label: 'Chargeback' },
        { value: 'Purchase_Request_Canceled', label: 'Compra Cancelada' },
        { value: 'Purchase_Request_Confirmed_Boleto', label: 'Boleto Gerado' },
        { value: 'Purchase_Request_Confirmed_Pix', label: 'PIX Gerado' },
        { value: 'Purchase_Request_Expired_Boleto', label: 'Boleto Expirado' },
        { value: 'Purchase_Request_Expired_Pix', label: 'PIX Expirado' },
        { value: 'Abandoned_Cart', label: 'Carrinho Abandonado' },
        { value: 'Recurrent_Payment', label: 'Assinatura Renovada' },
        { value: 'Subscription_Canceled', label: 'Assinatura Cancelada' },
        { value: 'Subscription_Renewal_Pending', label: 'Assinatura Atrasada' },
        { value: 'Refund_Period_Over', label: 'Compra Concluída (Pós-Garantia)' },
    ],
    guru: [
        { value: 'approved', label: 'Compra Aprovada' },
        { value: 'approved_order_bump', label: 'Compra Aprovada (Order Bump)' },
        { value: 'approved_upsell', label: 'Compra Aprovada (Upsell)' },
        { value: 'refused', label: 'Cartão Recusado' },
        { value: 'canceled', label: 'Compra Cancelada' },
        { value: 'refunded', label: 'Reembolso' },
        { value: 'chargeback', label: 'Chargeback' },
        { value: 'billet_printed', label: 'Boleto Gerado' },
        { value: 'expired_billet', label: 'Boleto Expirado' },
        { value: 'waiting_payment_pix', label: 'PIX Gerado' },
        { value: 'expired_pix', label: 'PIX Expirado' },
        { value: 'abandoned', label: 'Carrinho Abandonado' },
        { value: 'subscription_active', label: 'Assinatura Renovada' },
        { value: 'subscription_canceled', label: 'Assinatura Cancelada' },
        { value: 'subscription_delayed', label: 'Assinatura Atrasada' },
    ],
    herospark: [
        { value: 'PURCHASE_APPROVED', label: 'Compra Aprovada' },
        { value: 'PURCHASE_APPROVED_order_bump', label: 'Compra Aprovada (Order Bump)' },
        { value: 'PURCHASE_APPROVED_upsell', label: 'Compra Aprovada (Upsell)' },
        { value: 'PURCHASE_CANCELED_card', label: 'Cartão Recusado' },
        { value: 'PURCHASE_REFUNDED', label: 'Reembolso' },
        { value: 'PURCHASE_CHARGEBACK', label: 'Chargeback' },
        { value: 'PURCHASE_BILLET_PRINTED_boleto', label: 'Boleto Gerado' },
        { value: 'PURCHASE_BILLET_PRINTED_pix', label: 'PIX Gerado' },
        { value: 'PURCHASE_EXPIRED_boleto', label: 'Boleto Expirado' },
        { value: 'PURCHASE_EXPIRED_pix', label: 'PIX Expirado' },
        { value: 'PURCHASE_OUT_OF_SHOPPING_CART', label: 'Carrinho Abandonado' },
        { value: 'SUBSCRIPTION_RENEWED', label: 'Assinatura Renovada' },
        { value: 'SUBSCRIPTION_CANCELED', label: 'Assinatura Cancelada' },
        { value: 'PURCHASE_DELAYED', label: 'Assinatura Atrasada' },
    ],
    greenn: [
        { value: 'sale_paid', label: 'Compra Aprovada' },
        { value: 'sale_paid_order_bump', label: 'Compra Aprovada (Order Bump)' },
        { value: 'sale_paid_upsell', label: 'Compra Aprovada (Upsell)' },
        { value: 'sale_refused_card', label: 'Cartão Recusado' },
        { value: 'sale_refunded', label: 'Reembolso' },
        { value: 'sale_chargedback', label: 'Chargeback' },
        { value: 'sale_waiting_boleto', label: 'Boleto Gerado' },
        { value: 'sale_waiting_pix', label: 'PIX Gerado' },
        { value: 'sale_refused_boleto', label: 'Boleto Expirado' },
        { value: 'sale_refused_pix', label: 'PIX Expirado' },
        { value: 'lead_abandoned', label: 'Carrinho Abandonado' },
        { value: 'contract_paid', label: 'Assinatura Renovada' },
        { value: 'contract_canceled', label: 'Assinatura Cancelada' },
        { value: 'contract_unpaid', label: 'Assinatura Atrasada' },
    ],
    hubla: [
        { value: 'invoice.payment_succeeded', label: 'Compra Aprovada' },
        { value: 'invoice.payment_failed_card', label: 'Cartão Recusado' },
        { value: 'invoice.refunded', label: 'Reembolso' },
        { value: 'invoice.status_updated_chargeback', label: 'Chargeback' },
        { value: 'invoice.created_boleto', label: 'Boleto Gerado' },
        { value: 'invoice.created_pix', label: 'PIX Gerado' },
        { value: 'invoice.expired_boleto', label: 'Boleto Expirado' },
        { value: 'invoice.expired_pix', label: 'PIX Expirado' },
        { value: 'lead.abandoned_cart', label: 'Carrinho Abandonado' },
        { value: 'subscription.activated', label: 'Assinatura Renovada' },
        { value: 'subscription.deactivated', label: 'Assinatura Cancelada' },
        { value: 'subscription.expiring', label: 'Assinatura Atrasada' },
    ],
    elementor: [
        { value: 'form_submission_flat', label: 'Formulário (fields[x][value])' },
        { value: 'form_submission_simple', label: 'Formulário (name/email/phone simples)' },
        { value: 'form_submission_nested', label: 'Formulário (fields aninhado WP)' },
    ],
    pagtrust: [
        { value: 'approved', label: 'Compra Aprovada' },
        { value: 'approved_order_bump', label: 'Compra Aprovada (Order Bump)' },
        { value: 'refused', label: 'Cartão Recusado (Crédito)' },
        { value: 'refused_pix', label: 'PIX Expirado' },
        { value: 'canceled', label: 'Cancelada' },
        { value: 'refunded', label: 'Reembolso' },
        { value: 'chargeback', label: 'Chargeback' },
        { value: 'pending_boleto', label: 'Boleto Gerado' },
        { value: 'pending_pix', label: 'PIX Gerado' },
        { value: 'abandoned_cart', label: 'Carrinho Abandonado' },
    ],
    zapgroup: [
        { value: 'lead_extraido', label: 'Lead Extraído de Grupo' },
    ],
};
