from fastapi import APIRouter

from .common_filters import (
    BulkDeleteRequest,
    extract_ddi_ddd,
    _apply_common_lead_filters,
    _get_related_client_ids,
    _get_blocked_suffixes,
    _get_resting_suffix_map,
    _phone_suffix,
)
from .query_routes import (
    router as query_router,
    list_leads,
    get_lead_ddi_ddd_filters,
    get_lead_filters,
    get_lead_custom_variables,
    export_leads_csv,
)
from .crud_routes import (
    router as crud_router,
    _delete_lead_and_relations,
    reset_lead_template_history,
    create_manual_lead,
    delete_lead,
    update_lead,
    clean_corrupted_tags,
    toggle_lead_lock,
    validate_contacts_for_bulk,
    _fix_mojibake,
    _normalize_name,
)
from .bulk_ops import (
    router as bulk_router,
    bulk_delete_leads,
    bulk_delete_all_leads,
    bulk_tag_leads,
    bulk_tag_all_leads,
    bulk_untag_leads,
    bulk_untag_all_leads,
    bulk_block_leads,
    bulk_unblock_leads,
    bulk_unblock_all_leads,
    bulk_block_all_leads,
    bulk_rest_leads,
    bulk_rest_all_leads,
    BulkDeleteAllRequest,
    BulkTagRequest,
    BulkTagAllRequest,
    BulkBlockRequest,
    BulkBlockAllRequest,
    BulkRestRequest,
    BulkRestAllRequest,
)

router = APIRouter()
router.include_router(query_router)
router.include_router(crud_router)
router.include_router(bulk_router)

__all__ = [
    "router",
    "BulkDeleteRequest",
    "extract_ddi_ddd",
    "_apply_common_lead_filters",
    "_get_related_client_ids",
    "_get_blocked_suffixes",
    "_get_resting_suffix_map",
    "_phone_suffix",
    "list_leads",
    "get_lead_ddi_ddd_filters",
    "get_lead_filters",
    "get_lead_custom_variables",
    "export_leads_csv",
    "_delete_lead_and_relations",
    "reset_lead_template_history",
    "create_manual_lead",
    "delete_lead",
    "update_lead",
    "clean_corrupted_tags",
    "toggle_lead_lock",
    "validate_contacts_for_bulk",
    "_fix_mojibake",
    "_normalize_name",
    "bulk_delete_leads",
    "bulk_delete_all_leads",
    "bulk_tag_leads",
    "bulk_tag_all_leads",
    "bulk_untag_leads",
    "bulk_untag_all_leads",
    "bulk_block_leads",
    "bulk_unblock_leads",
    "bulk_unblock_all_leads",
    "bulk_block_all_leads",
    "bulk_rest_leads",
    "bulk_rest_all_leads",
    "BulkDeleteAllRequest",
    "BulkTagRequest",
    "BulkTagAllRequest",
    "BulkBlockRequest",
    "BulkBlockAllRequest",
    "BulkRestRequest",
    "BulkRestAllRequest",
]
